#!/usr/bin/env python3
"""Generate samples/sandbox/assets/sprites.png, the sandbox's sprite sheet.

Foundry's own content, under the repository's licence. Committed as a PNG because the
sandbox decodes it with the engine's decoder at startup, and generated by a script so the
binary in the tree is reproducible rather than mysterious.

A 4x4 grid of 16x16 cells: four shapes across four hues, all with hard transparent edges,
because a transparent edge is what makes a wrong blend mode or a wrong UV obvious.

Run from the repository root.
"""

import binascii
import colorsys
import os
import struct
import zlib

CELL = 16
GRID = 4
SIZE = CELL * GRID


def chunk(kind: bytes, data: bytes) -> bytes:
    return (struct.pack(">I", len(data)) + kind + data
            + struct.pack(">I", binascii.crc32(kind + data) & 0xFFFFFFFF))


def shape_alpha(shape: int, x: float, y: float) -> float:
    """1 inside the shape, 0 outside. `x` and `y` are in -1..1 within the cell."""
    if shape == 0:                                  # disc
        return 1.0 if x * x + y * y <= 0.8 else 0.0
    if shape == 1:                                  # diamond
        return 1.0 if abs(x) + abs(y) <= 0.9 else 0.0
    if shape == 2:                                  # ring
        r = (x * x + y * y) ** 0.5
        return 1.0 if 0.45 <= r <= 0.9 else 0.0
    return 1.0 if abs(x) <= 0.28 or abs(y) <= 0.28 else 0.0   # plus


def main():
    rows = []
    for py in range(SIZE):
        row = bytearray()
        for px in range(SIZE):
            cell_x, cell_y = px // CELL, py // CELL
            index = cell_y * GRID + cell_x

            # -1..1 across the cell, sampled at pixel centres.
            x = ((px % CELL) + 0.5) / CELL * 2 - 1
            y = ((py % CELL) + 0.5) / CELL * 2 - 1

            alpha = shape_alpha(index % GRID, x, y)
            hue = (index // GRID) / GRID + (index % GRID) / (GRID * GRID * 2)
            # Shade towards the edge so a scaled-up sprite shows its filtering.
            value = 1.0 - 0.35 * min(1.0, (x * x + y * y) ** 0.5)
            r, g, b = colorsys.hsv_to_rgb(hue, 0.65, value)

            if alpha == 0.0:
                # Fully transparent pixels keep a sensible colour so that a renderer
                # which forgets to premultiply shows dark fringes rather than nothing.
                row += bytes([0, 0, 0, 0])
            else:
                row += bytes([int(r * 255), int(g * 255), int(b * 255), 255])
        rows.append(row)

    raw = bytearray()
    for row in rows:
        raw.append(0)          # filter: none. The sheet is tiny; clarity beats bytes.
        raw += row

    png = bytearray(b"\x89PNG\r\n\x1a\n")
    png += chunk(b"IHDR", struct.pack(">IIBBBBB", SIZE, SIZE, 8, 6, 0, 0, 0))
    png += chunk(b"IDAT", zlib.compress(bytes(raw), 9))
    png += chunk(b"IEND", b"")

    out = os.path.join("samples", "sandbox", "assets", "sprites.png")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "wb") as f:
        f.write(png)
    print(f"wrote {out}, {len(png)} bytes, {SIZE}x{SIZE}, {GRID * GRID} cells")


if __name__ == "__main__":
    main()
