#!/usr/bin/env python3
"""Generate samples/sandbox/content/sounds/*.wav, the sandbox's sounds.

Foundry's own content, under the repository's licence. Committed as WAVs because the
sandbox decodes them with the engine's decoder at startup, and generated by a script so
the binaries in the tree are reproducible rather than mysterious — the same bargain
`gen-sandbox-sprites.py` makes for the sprite sheet.

Three sounds, chosen to exercise three different things rather than to sound good:

  step.wav  22050 Hz, ~70 ms   a noise tick. Its rate is not the device's, so playing it
                               runs the voice's resampler on the real path.
  bump.wav  48000 Hz, ~160 ms  a low thud at the device's own rate, so the same path is
                               also exercised with no resampling at all.
  hum.wav   24000 Hz, 500 ms   a seamless loop: every partial completes a whole number of
                               cycles inside it, so the wrap is silent.

All mono 16-bit PCM, which is the format an author is most likely to hand the engine.

Run from the repository root.
"""

import math
import os
import struct

OUT_DIR = os.path.join("samples", "sandbox", "content", "sounds")


def write_wav(name: str, rate: int, frames: list[float]) -> None:
    """One mono 16-bit PCM file. Samples are clamped, not scaled: a generator that
    overshoots should be fixed here rather than quietly made quieter."""
    pcm = bytearray()
    for value in frames:
        clamped = max(-1.0, min(1.0, value))
        pcm += struct.pack("<h", int(round(clamped * 32767)))

    header = b"RIFF" + struct.pack("<I", 36 + len(pcm)) + b"WAVE"
    header += b"fmt " + struct.pack("<IHHIIHH", 16, 1, 1, rate, rate * 2, 2, 16)
    header += b"data" + struct.pack("<I", len(pcm))

    os.makedirs(OUT_DIR, exist_ok=True)
    path = os.path.join(OUT_DIR, name)
    with open(path, "wb") as f:
        f.write(header + bytes(pcm))
    print(f"wrote {path}, {len(header) + len(pcm)} bytes, {len(frames)} frames at {rate} Hz")


def noise(seed: int):
    """A tiny LCG, so the committed bytes are the same on every machine and in every
    Python version — `random` is not promised to be."""
    state = seed
    while True:
        state = (state * 1664525 + 1013904223) & 0xFFFFFFFF
        yield state / 0x80000000 - 1.0


def step_tick(rate: int = 22050, ms: int = 70) -> list[float]:
    count = rate * ms // 1000
    source = noise(0x5EED)
    out = []
    previous = 0.0
    for i in range(count):
        # A one-pole lowpass over white noise, so it is a tick rather than a hiss, with a
        # short exponential decay and a linear tail to zero. The tail matters: a sample
        # that stops mid-amplitude clicks on its own.
        previous = 0.55 * previous + 0.45 * next(source)
        envelope = math.exp(-9.0 * i / count) * (1.0 - i / count)
        out.append(0.55 * previous * envelope)
    return out


def bump_thud(rate: int = 48000, ms: int = 160) -> list[float]:
    count = rate * ms // 1000
    out = []
    for i in range(count):
        t = i / rate
        # A pitch that falls as it decays, which is what a soft collision sounds like.
        frequency = 150.0 * math.exp(-6.0 * i / count) + 45.0
        envelope = math.exp(-7.0 * i / count) * (1.0 - i / count)
        out.append(0.7 * math.sin(2.0 * math.pi * frequency * t) * envelope)
    return out


def hum_loop(rate: int = 24000, ms: int = 500) -> list[float]:
    count = rate * ms // 1000
    out = []
    for i in range(count):
        phase = i / count
        # 110 Hz and 220 Hz complete 55 and 110 whole cycles in half a second, so the end
        # of the buffer meets its beginning at the same phase and the loop is seamless.
        # A frequency that did not divide evenly would put a click on every wrap, which is
        # the one artefact a looping ambience cannot hide.
        out.append(
            0.11 * math.sin(2.0 * math.pi * 55.0 * phase)
            + 0.045 * math.sin(2.0 * math.pi * 110.0 * phase)
        )
    return out


def main() -> None:
    write_wav("step.wav", 22050, step_tick())
    write_wav("bump.wav", 48000, bump_thud())
    write_wav("hum.wav", 24000, hum_loop())


if __name__ == "__main__":
    main()
