#!/usr/bin/env python3
"""Generate the PNG fixtures used by engine/src/asset/png.zig's tests.

These are written by an implementation that shares no code with the decoder under test —
that is the entire point. A fixture built with our own filter routines would agree with
our own bugs. Python's zlib also produces a real Huffman-coded stream, which the
hand-assembled stored-block fixtures in the test file do not exercise.

Run from the repository root; prints Zig source to stdout.
"""

import binascii
import struct
import zlib


def chunk(kind: bytes, data: bytes) -> bytes:
    return (struct.pack(">I", len(data)) + kind + data
            + struct.pack(">I", binascii.crc32(kind + data) & 0xFFFFFFFF))


def paeth(a: int, b: int, c: int) -> int:
    p = a + b - c
    pa, pb, pc = abs(p - a), abs(p - b), abs(p - c)
    if pa <= pb and pa <= pc:
        return a
    if pb <= pc:
        return b
    return c


def filter_rows(rows, bpp, filter_type):
    """Apply one filter type to every scanline. `rows` is a list of bytearrays."""
    out = bytearray()
    prev = bytearray(len(rows[0]))
    for row in rows:
        out.append(filter_type)
        line = bytearray()
        for i, value in enumerate(row):
            left = row[i - bpp] if i >= bpp else 0
            above = prev[i]
            corner = prev[i - bpp] if i >= bpp else 0
            if filter_type == 0:
                pred = 0
            elif filter_type == 1:
                pred = left
            elif filter_type == 2:
                pred = above
            elif filter_type == 3:
                pred = (left + above) // 2
            elif filter_type == 4:
                pred = paeth(left, above, corner)
            line.append((value - pred) & 0xFF)
        out += line
        prev = row
    return bytes(out)


def png(width, height, color_type, bit_depth, rows, bpp, filter_type,
        palette=None, trns=None, interlace=0):
    out = bytearray(b"\x89PNG\r\n\x1a\n")
    out += chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, bit_depth,
                                      color_type, 0, 0, interlace))
    if palette is not None:
        out += chunk(b"PLTE", palette)
    if trns is not None:
        out += chunk(b"tRNS", trns)
    out += chunk(b"IDAT", zlib.compress(filter_rows(rows, bpp, filter_type), 9))
    out += chunk(b"IEND", b"")
    return bytes(out)


def zig_bytes(name: str, data: bytes, doc: str) -> str:
    lines = [f"/// {doc}", f"const {name} = [_]u8{{"]
    for i in range(0, len(data), 12):
        row = ", ".join(f"0x{b:02X}" for b in data[i:i + 12])
        lines.append(f"    {row},")
    lines.append("};")
    return "\n".join(lines)


def main():
    # A 4x4 RGBA image with a deliberately non-uniform pattern, Paeth-filtered: the
    # filter whose predictor is easiest to get subtly wrong.
    rgba_pixels = []
    for y in range(4):
        row = bytearray()
        for x in range(4):
            row += bytes([x * 60 + 10, y * 60 + 20, (x ^ y) * 40 + 5, 255 - y * 50])
        rgba_pixels.append(row)
    rgba = png(4, 4, 6, 8, rgba_pixels, 4, 4)

    # The same pixels, Average-filtered, so the two must decode identically.
    rgba_avg = png(4, 4, 6, 8, rgba_pixels, 4, 3)

    # 3x2 palette with tRNS shorter than the palette, so the tail defaults to opaque.
    palette = bytes([255, 0, 0, 0, 255, 0, 0, 0, 255, 255, 255, 0])
    trns = bytes([0, 128])
    pal_rows = [bytearray([0, 1, 2]), bytearray([3, 2, 1])]
    pal = png(3, 2, 3, 8, pal_rows, 1, 1, palette=palette, trns=trns)

    # 2x2 greyscale at 16 bits: valid PNG, outside the subset.
    grey16 = png(2, 2, 0, 16, [bytearray([0, 0, 255, 255]),
                               bytearray([128, 0, 64, 0])], 2, 0)

    # 4x4 RGBA, Adam7 interlaced. The IDAT is nonsense for a real interlaced file;
    # the header is what must be refused, and it must be refused before that matters.
    inter = png(4, 4, 6, 8, rgba_pixels, 4, 0, interlace=1)

    print("// Generated by scripts/gen-test-pngs.py. Do not edit by hand.")
    print()
    print(zig_bytes("png_rgba_paeth", rgba, "4x4 RGBA, every scanline Paeth-filtered."))
    print()
    print(zig_bytes("png_rgba_average", rgba_avg,
                    "The same 4x4 image, Average-filtered. Must decode identically."))
    print()
    print(zig_bytes("png_palette_trns", pal,
                    "3x2 palette image with a tRNS shorter than the palette."))
    print()
    print(zig_bytes("png_grayscale_16bit", grey16,
                    "2x2 greyscale at 16 bits: valid PNG, outside the subset."))
    print()
    print(zig_bytes("png_interlaced", inter, "4x4 RGBA declaring Adam7 interlacing."))
    print()

    expected = bytearray()
    for row in rgba_pixels:
        expected += row
    print(zig_bytes("expected_rgba", bytes(expected),
                    "The 4x4 image's pixels, RGBA, top row first."))


if __name__ == "__main__":
    main()
