#!/usr/bin/env python3
"""Generate samples/room/content/ art and sounds — the room sample's own assets.

Foundry's own content, under the repository's licence. Committed as PNG and WAV because
the sample decodes them with the engine's own decoders at startup, and generated by a
script so the binaries in the tree are reproducible rather than mysterious — the same
bargain `gen-sandbox-sprites.py` and `gen-sandbox-sounds.py` make.

**These are the room's, not the sandbox's.** A package owns its files, and two samples
sharing a sheet would make one of them depend on the other's directory layout, which is
exactly what ADR-0021 exists to prevent.

One 4x4 sheet of 16x16 cells, whose first row is the tileset and whose rest is everything
the room draws as a sprite:

  0 floor   1 wall   2 threshold   3 rug
  4-7       the walker, four frames
  8         a lamp, unlit
  9-11      a lamp, lit — three frames of glow, so lighting one is visible from across
            the room rather than only underfoot
  12        the door
  13        flat white, for the text panel to tint

Five sounds, all mono 16-bit PCM at four different rates, because a game hands the mixer
whatever its authors had:

  step.wav   22050 Hz   a soft footfall
  bump.wav   48000 Hz   walking into something
  chime.wav  32000 Hz   a lamp catching
  open.wav   44100 Hz   the door
  hum.wav    24000 Hz   the door's own note, looping seamlessly

Run from the repository root.
"""

import binascii
import math
import os
import struct
import zlib

CELL = 16
GRID = 4
SIZE = CELL * GRID

TEXTURES = os.path.join("samples", "room", "content", "textures")
SOUNDS = os.path.join("samples", "room", "content", "sounds")


# -- the sheet -----------------------------------------------------------------------

def chunk(kind: bytes, data: bytes) -> bytes:
    return (struct.pack(">I", len(data)) + kind + data
            + struct.pack(">I", binascii.crc32(kind + data) & 0xFFFFFFFF))


class Sheet:
    def __init__(self):
        self.buf = bytearray(SIZE * SIZE * 4)

    def put(self, cell: int, x: int, y: int, rgba) -> None:
        if not (0 <= x < CELL and 0 <= y < CELL):
            return
        px = (cell % GRID) * CELL + x
        py = (cell // GRID) * CELL + y
        at = (py * SIZE + px) * 4
        self.buf[at:at + 4] = bytes(rgba)

    def fill(self, cell: int, rgba) -> None:
        for y in range(CELL):
            for x in range(CELL):
                self.put(cell, x, y, rgba)


def hashed(x: int, y: int, salt: int) -> int:
    """A stable per-pixel value. Not `random`, whose stream is not promised across
    versions, and the committed bytes have to be the same on every machine."""
    v = (x * 374761393 + y * 668265263 + salt * 2246822519) & 0xFFFFFFFF
    v ^= v >> 13
    v = (v * 1274126177) & 0xFFFFFFFF
    return v >> 16


def floor_cell(s: Sheet) -> None:
    for y in range(CELL):
        for x in range(CELL):
            n = hashed(x, y, 1) % 11
            s.put(0, x, y, (36 + n, 41 + n, 52 + n, 255))
            # A faint grout line, so a floor of identical tiles still reads as tiles.
            if x == 0 or y == 0:
                s.put(0, x, y, (30, 34, 44, 255))


def wall_cell(s: Sheet) -> None:
    for y in range(CELL):
        for x in range(CELL):
            n = hashed(x, y, 2) % 9
            s.put(1, x, y, (74 + n, 80 + n, 98 + n, 255))
    # Bevelled: light along the top and left, dark along the bottom and right. It is the
    # cheapest thing that makes a flat colour look like it has a front face.
    for i in range(CELL):
        s.put(1, i, 0, (104, 112, 134, 255))
        s.put(1, 0, i, (96, 104, 126, 255))
        s.put(1, i, CELL - 1, (44, 48, 62, 255))
        s.put(1, CELL - 1, i, (52, 56, 72, 255))


def threshold_cell(s: Sheet) -> None:
    for y in range(CELL):
        for x in range(CELL):
            n = hashed(x, y, 3) % 7
            s.put(2, x, y, (44 + n, 82 + n, 62 + n, 255))
    # An arrow pointing up — north, in the map as written — so the way out looks like one.
    for y in range(8, 14):
        for x in (7, 8):
            s.put(2, x, y, (150, 220, 170, 255))
    for dy in range(6):
        y = 3 + dy
        for x in range(7 - dy, 9 + dy):
            s.put(2, x, y, (150, 220, 170, 255))


def rug_cell(s: Sheet) -> None:
    for y in range(CELL):
        for x in range(CELL):
            edge = min(x, y, CELL - 1 - x, CELL - 1 - y)
            base = (78, 58, 86) if edge >= 2 else (58, 42, 66)
            n = hashed(x, y, 4) % 6
            s.put(3, x, y, (base[0] + n, base[1] + n, base[2] + n, 255))
            if edge >= 4 and (x + y) % 6 == 0:
                s.put(3, x, y, (128, 96, 140, 255))


BODY = (255, 224, 168, 255)
SHADE = (206, 172, 118, 255)
DARK = (72, 54, 36, 255)


def walker(s: Sheet, cell: int, phase: int) -> None:
    """One frame of the walk. `phase` is 0..3; 0 and 2 stand, 1 and 3 stride."""
    # Head.
    for y in range(2, 6):
        for x in range(6, 10):
            s.put(cell, x, y, BODY)
    for x in range(6, 10):
        s.put(cell, x, 2, SHADE)
    s.put(cell, 6, 3, DARK)
    s.put(cell, 9, 3, DARK)
    # Torso.
    for y in range(6, 11):
        for x in range(5, 11):
            s.put(cell, x, y, BODY if x < 9 else SHADE)
    # Legs. The stride swaps which foot is forward, which is what makes four frames read
    # as walking rather than as bobbing.
    left = 0 if phase in (0, 2) else (-1 if phase == 1 else 1)
    right = -left
    for y in range(11, 15):
        s.put(cell, 6 + left, y, BODY)
        s.put(cell, 9 + right, y, SHADE)
    s.put(cell, 6 + left, 15, DARK)
    s.put(cell, 9 + right, 15, DARK)


def lamp(s: Sheet, cell: int, glow: int) -> None:
    """A lamp. `glow` is 0 for unlit, then 1..3 for widening light."""
    # Stand.
    for y in range(11, 16):
        s.put(cell, 7, y, (120, 114, 146, 255))
        s.put(cell, 8, y, (92, 86, 116, 255))
    for x in range(5, 11):
        s.put(cell, x, 15, (120, 114, 146, 255))
    # Bulb.
    for y in range(5, 12):
        for x in range(5, 11):
            if (x - 7.5) ** 2 / 9 + (y - 8) ** 2 / 12 > 1.0:
                continue
            s.put(cell, x, y, (104, 108, 138, 255) if glow == 0 else (255, 214, 128, 255))
    if glow == 0:
        # An unlit lamp catches a little of what light there is. Without this it is four
        # pixels darker than the floor it stands on, and a lamp a player cannot find is a
        # room they walk in circles around -- which is a level design problem being caused
        # by a sprite.
        for y in range(4, 13):
            for x in range(4, 12):
                d = math.hypot(x - 7.5, y - 8.0)
                if d <= 2.6 or d > 5.2:
                    continue
                a = int(70 * (1.0 - (d - 2.6) / 2.6))
                if a > 0:
                    s.put(cell, x, y, (150, 160, 200, a))
        # A highlight on the glass, so it reads as a bulb rather than as a smudge.
        s.put(cell, 6, 6, (188, 194, 224, 255))
        s.put(cell, 7, 6, (150, 158, 194, 255))
        return
    # A halo whose radius is the frame. Alpha, so it reads as light rather than as a disc.
    radius = 4.0 + glow * 1.6
    for y in range(CELL):
        for x in range(CELL):
            d = math.hypot(x - 7.5, y - 8.0)
            if d <= 3.0 or d > radius:
                continue
            a = int(150 * (1.0 - (d - 3.0) / (radius - 3.0)))
            if a > 0:
                s.put(cell, x, y, (255, 196, 108, a))


def door_cell(s: Sheet) -> None:
    for y in range(CELL):
        for x in range(CELL):
            n = hashed(x, y, 5) % 8
            s.put(12, x, y, (122 + n, 88 + n, 56 + n, 255))
    for y in range(CELL):
        s.put(12, 0, y, (70, 50, 32, 255))
        s.put(12, CELL - 1, y, (70, 50, 32, 255))
        s.put(12, 7, y, (92, 66, 42, 255))
    for x in range(CELL):
        s.put(12, x, 2, (150, 112, 72, 255))
        s.put(12, x, CELL - 3, (150, 112, 72, 255))


def write_sheet() -> None:
    s = Sheet()
    floor_cell(s)
    wall_cell(s)
    threshold_cell(s)
    rug_cell(s)
    for i in range(4):
        walker(s, 4 + i, i)
    lamp(s, 8, 0)
    for i in range(3):
        lamp(s, 9 + i, i + 1)
    door_cell(s)
    s.fill(13, (255, 255, 255, 255))

    raw = bytearray()
    for y in range(SIZE):
        raw.append(0)                       # filter: none. Small sheet; clarity beats bytes.
        raw += s.buf[y * SIZE * 4:(y + 1) * SIZE * 4]

    png = bytearray(b"\x89PNG\r\n\x1a\n")
    png += chunk(b"IHDR", struct.pack(">IIBBBBB", SIZE, SIZE, 8, 6, 0, 0, 0))
    png += chunk(b"IDAT", zlib.compress(bytes(raw), 9))
    png += chunk(b"IEND", b"")

    os.makedirs(TEXTURES, exist_ok=True)
    out = os.path.join(TEXTURES, "room.png")
    with open(out, "wb") as f:
        f.write(png)
    print(f"wrote {out}, {len(png)} bytes, {SIZE}x{SIZE}, {GRID * GRID} cells")


# -- the sounds ----------------------------------------------------------------------

def write_wav(name: str, rate: int, frames) -> None:
    pcm = bytearray()
    for value in frames:
        clamped = max(-1.0, min(1.0, value))
        pcm += struct.pack("<h", int(round(clamped * 32767)))

    header = b"RIFF" + struct.pack("<I", 36 + len(pcm)) + b"WAVE"
    header += b"fmt " + struct.pack("<IHHIIHH", 16, 1, 1, rate, rate * 2, 2, 16)
    header += b"data" + struct.pack("<I", len(pcm))

    os.makedirs(SOUNDS, exist_ok=True)
    path = os.path.join(SOUNDS, name)
    with open(path, "wb") as f:
        f.write(header + bytes(pcm))
    print(f"wrote {path}, {len(header) + len(pcm)} bytes, {len(frames)} frames at {rate} Hz")


def noise(seed: int):
    state = seed
    while True:
        state = (state * 1664525 + 1013904223) & 0xFFFFFFFF
        yield state / 0x80000000 - 1.0


def step(rate: int = 22050, ms: int = 90):
    count = rate * ms // 1000
    src = noise(0x0BEEF)
    out, low = [], 0.0
    for i in range(count):
        low = 0.72 * low + 0.28 * next(src)
        env = math.exp(-11.0 * i / count) * (1.0 - i / count)
        out.append(0.42 * low * env)
    return out


def bump(rate: int = 48000, ms: int = 170):
    count = rate * ms // 1000
    src = noise(0x1CE)
    out, low = [], 0.0
    for i in range(count):
        t = i / rate
        low = 0.90 * low + 0.10 * next(src)
        env = math.exp(-15.0 * i / count) * (1.0 - i / count)
        tone = math.sin(2 * math.pi * 96.0 * t)
        out.append((0.62 * tone + 0.38 * low) * env * 0.7)
    return out


def chime(rate: int = 32000, ms: int = 620):
    """A lamp catching: three partials of one bell, decaying at different speeds so the
    tail changes colour rather than only getting quieter."""
    count = rate * ms // 1000
    partials = ((1.0, 0.55, 4.0), (2.02, 0.28, 6.5), (3.01, 0.17, 9.0))
    out = []
    for i in range(count):
        t = i / rate
        v = 0.0
        for ratio, gain, decay in partials:
            v += gain * math.sin(2 * math.pi * 784.0 * ratio * t) * math.exp(-decay * t)
        # A short attack, so the onset is not a click.
        attack = min(1.0, i / (rate * 0.004))
        out.append(0.7 * v * attack * (1.0 - i / count))
    return out


def open_door(rate: int = 44100, ms: int = 900):
    """A rising sweep with a scrape over it. Long, because it is the sound of the sample
    being won and it should be unmistakable."""
    count = rate * ms // 1000
    src = noise(0xD001)
    out, low, phase = [], 0.0, 0.0
    for i in range(count):
        u = i / count
        freq = 110.0 + 260.0 * u * u
        phase += 2 * math.pi * freq / rate
        low = 0.85 * low + 0.15 * next(src)
        env = min(1.0, i / (rate * 0.02)) * (1.0 - u) ** 0.7
        out.append((0.55 * math.sin(phase) + 0.30 * low) * env * 0.8)
    return out


def hum(rate: int = 24000, ms: int = 1000):
    """The door's note, and it has to loop without a seam: every partial completes a whole
    number of cycles in the file, so the wrap lands where the waveform already was."""
    count = rate * ms // 1000
    seconds = count / rate
    out = []
    for i in range(count):
        t = i / rate
        v = 0.0
        for cycles, gain in ((55, 0.55), (110, 0.24), (165, 0.12)):
            v += gain * math.sin(2 * math.pi * cycles * t / seconds)
        out.append(0.34 * v)
    return out


def main():
    write_sheet()
    write_wav("step.wav", 22050, step())
    write_wav("bump.wav", 48000, bump())
    write_wav("chime.wav", 32000, chime())
    write_wav("open.wav", 44100, open_door())
    write_wav("hum.wav", 24000, hum())


if __name__ == "__main__":
    main()
